### ISSUE TITLE
Use new icon on flathub

### ISSUE THREAD

**Issue by lightonflux** [flathub/org.gnome.gitlab.cheywood.Iotas#1]
The newest version changed the icon. It is easy to spot because the ribbon is now blue. 

While the app has the correct icon the flathub store does not. 

https://gitlab.gnome.org/cheywood/iotas/-/blob/main/data/icons/hicolor/scalable/apps/org.gnome.gitlab.cheywood.Iotas.svg

**Comment by cheywood** [comment]
I believe this one is resolved now, please reopen I'm wrong.

Thanks @lightonflux, sorry for the very slow response!
